### ISSUE TITLE
Create DB Package GitHub Workflow

### ISSUE THREAD

**Issue by Jesus-15** [BUAdvDev2023/Rest-Auth-API#11]

**Comment by 3miliof** [comment]
Hi Jesus, investigated this after our chat earlier today. 

To create a package with the 'build and publish docker image' github action, it has to access a dockerfile to build the image from. As the database is built off of the official mysql image, simply pulled into the docker compose, I don't think it is possible to package it as its own thing here. 

A solution may be to include an example-compose type file for people to copy and paste into their own compose. With the image link created from the gchr.io link for the API and mysql:latest for the db.
