### ISSUE TITLE
Feature req: able to send RESTful requests using username

### ISSUE THREAD

**Issue by Grandevity** [BUAdvDev2023/Rest-Auth-API#14]
at the moment we only have routes that use Query param ID, which is fine, but means I have to store the ID in a cookie until I need it for user update requests etc. Might be beneficial to add fetch/update/delete routes using username as a separate alternative, it would help me out massively! :)

**Comment by Jesus-15** [comment]
Hi, I have added this functionality. Now you can do all the functions with username or id.
