### ISSUE TITLE
Hiding unique keys and moving the flask config to another file.

### ISSUE THREAD

**Issue by JM1F** [BUAdvDev2023/Rest-Auth-API#19]
Hi,

The repository is currently public and everyone outside BUAdvDev can see the flask configuration, including the secret key.

![image](https://github.com/BUAdvDev2023/Rest-Auth-API/assets/71614127/e7513123-a579-4087-a2d3-cb94f8971d5a)

It is generally good practice to move the config settings to a separate file (config.py) and include it in your .gitignore so it does not get committed.

**Comment by Jesus-15** [comment]
Hi,

I am aware of these settings, it was done like this so it simplifies the setup process for all the modules using the API.
