### ISSUE TITLE
Feature Request: Getting User Information

### ISSUE THREAD

**Issue by cierannolan** [BUAdvDev2023/Rest-Auth-API#21]
Hi,

Is it possible to request user information beyond usernames? From what I can tell, you are able to use user IDs and usernames to return usernames but no information beyond that. It would be nice to be able to request information (in my case 'role' especially). 

Also, if requests are going to take ID as a parameter, then there needs to be a way to retrieve user IDs outside of registration, or else requests aren't really accessible unless you have set the ID beforehand.

**Comment by Jesus-15** [comment]
Hi, 

I have made this functionality available in the code, you are able to get all the user information with get_user_username including the id.

Thanks,
